---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "12"

dist: xenial

addons:
  apt:
    packages:
      - dpkg
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script: npm run test:ember
    - script: npm run lint
      name: "Linter"

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - npm install --no-package-lock
      script:
        - npm run test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - name: "ember-lts-3.16"
      env: EMBER_TRY_SCENARIO=ember-lts-3.16
    - name: "ember-release"
      env: EMBER_TRY_SCENARIO=ember-release
    - name: "ember-beta"
      env: EMBER_TRY_SCENARIO=ember-beta
    - name: "ember-canary"
      env: EMBER_TRY_SCENARIO=ember-canary
    - name: "ember-default-with-jquery"
      env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - name: "ember-classic"
      env: EMBER_TRY_SCENARIO=ember-classic

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
